fields = {
    "Expression":u"絶",
    "Keyword":u"test",
    "Onyomi":u"オン、ホン",
    "Kunyomi":u"くん",
    "Kanji_story":u"Story to help me remember how to write this kanji: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at massa eget lacus feugiat ornare nec iaculis justo. Donec venenatis, ex vitae aliquet aliquam.",
    "Onyomi_story":u"Story to remember the on reading. Nam mollis, neque ut semper tristique, quam lectus pellentesque eros, quis iaculis eros massa in neque. Ut porttitor ac nulla sit amet aliquam. Aliquam venenatis faucibus mauris sed egestas. Vivamus bibendum placerat sodales. Praesent vel est viverra, aliquet nisi nec, luctus nibh. Vestibulum augue est, tristique a eros a, luctus venenatis neque. Fusce vehicula, massa pulvinar aliquam vehicula, nisl magna faucibus augue",
    "Kunyomi_story":u"Story to remember the kun reading. Sed nec scelerisque enim, sed luctus orci. Aliquam erat volutpat. Nulla ac viverra odio, nec aliquet ligula. Vivamus porttitor nisi in neque elementum facilisis. Proin maximus venenatis dolor, non dictum augue varius ac. Mauris eu dolor quis augue dapibus consequat. Morbi facilisis tor",
    "Combined_story":u"Story for both on and kun reading. Sed nec scelerisque enim, sed luctus orci.",
    "Kanji_image":u"",
    "Readings_image":u"",
    "Note":u"Some note here.",
    "Keyword_notes":u"",
    "Other_meanings":u"some otherOther meanings",
    "Number_of_readings":u"3",
    "Audio":u"",
    "Kanji_examples":u"",
    "Diagram":u"",
    "Heisig_index":"575",
    "Tags":"some_tag other tag",
    "Deck":"My_deck::deck",
    "Type":"Japanese_my_note_type",
    "Card":"my_awesome_test_note"
}