#!/bin/bash

echo "*** RENDERING KANJI CARDS ***"

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
main_dir="${this_dir}/.."

cd "${main_dir}/cards/japanese/kanji/"
sh "bulk_mock.sh"
cd -
echo "done. Press Enter to continue."

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

read continue
