#!/bin/bash

#set -e

echo "*** RENDERING KANJI CARDS ***"

sh $HOME/Documents/prog/japan/anki/cards/cards/japanese/kanji/bulk_mock.sh

echo "done. Press Enter to continue."

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

read continue
